import type {
  BaseSymbolData,
  DashboardFilters,
  MarketingFeature,
  MarketingStep,
  PricingTier,
  SavedFilterPreset,
  ScanLog,
} from "@/lib/market/types";

export const landingStats = [
  {
    label: "日次ランキング銘柄",
    value: "148",
    note: "デモ対象の小型株を 5 分ごとにスコアリング",
  },
  {
    label: "フラグ種類",
    value: "6",
    note: "出来高、値動き、ボラ、ギャップ、ニュース、ウォッチを重ねて判定",
  },
  {
    label: "平均スキャン遅延",
    value: "2.4s",
    note: "本日のユニバースを巡回するデモエンジンの処理速度",
  },
] as const;

export const howItWorksSteps: MarketingStep[] = [
  {
    title: "板を走査する",
    description:
      "GrassScan は、初動の異常を見つけやすい活動スコアで、カバーの薄い小型株を順位付けします。",
  },
  {
    title: "要因を確認する",
    description:
      "各銘柄では、出来高、値動きの強さ、ボラティリティ、モメンタム、仮のニュース加速を分解して確認できます。",
  },
  {
    title: "確信度で動く",
    description:
      "気になる銘柄をウォッチに保存し、前日比を見比べながら、スキャン履歴を継続的に追えます。",
  },
] as const;

export const marketingFeatures: MarketingFeature[] = [
  {
    title: "Bloomberg ライクな監視画面",
    description:
      "情報量は多くても読みやすい表、磨かれたダークパネル、スコア主導の可視化で反復監視に向きます。",
  },
  {
    title: "デモ起点のウォッチ運用",
    description:
      "ウォッチリストとデモモードはローカル保存され、インフラなしでも MVP を通しで試せます。",
  },
  {
    title: "実データ接続を見据えた構成",
    description:
      "モック銘柄、スコア計算、セレクタを分離しており、あとから実データプロバイダーを差し込みやすい構成です。",
  },
] as const;

export const pricingTiers: PricingTier[] = [
  {
    name: "スターター",
    price: "$0",
    description: "デモモードでワークフローを試したい個人トレーダー向け。",
    cta: "無料で始める",
    features: [
      "デモダッシュボードと銘柄詳細",
      "ローカル保存のウォッチリスト",
      "保存済みフィルターとランキング表示",
    ],
  },
  {
    name: "プロ",
    price: "$29",
    description: "実データ接続後に、より深いランキング分析を使いたいトレーダー向け。",
    cta: "ウェイトリストに参加",
    highlighted: true,
    features: [
      "より長いスキャン履歴",
      "有効化後のプロバイダー連携",
      "高度なスコア分解表示",
    ],
  },
  {
    name: "デスク",
    price: "$99",
    description: "より広いユニバースを扱う内部チームやパワーユーザー向け。",
    cta: "営業に相談",
    features: [
      "複数ユーザーのウォッチリスト",
      "管理者向けスキャン操作",
      "出力を前提にした内部ワークフロー",
    ],
  },
] as const;

export const defaultDashboardFilters: DashboardFilters = {
  query: "",
  priceUnder: "",
  minVolume: "",
  sector: "すべて",
  marketCapRange: "all",
  activityScoreThreshold: "35",
};

export const savedFilterPresets: SavedFilterPreset[] = [
  {
    id: "under_5",
    label: "$5以下",
    description: "群集化しやすい低位株を優先。",
    values: {
      priceUnder: "5",
    },
  },
  {
    id: "under_1",
    label: "$1以下",
    description: "ノイズも大きいが初動も出やすいナノキャップ。",
    values: {
      priceUnder: "1",
      marketCapRange: "nano",
    },
  },
  {
    id: "biotech",
    label: "バイオ",
    description: "治験や規制材料で動きやすい銘柄群。",
    values: {
      sector: "バイオテック",
    },
  },
  {
    id: "high_volume_only",
    label: "高出来高のみ",
    description: "すでに流動性が集まり始めた銘柄を優先。",
    values: {
      minVolume: "15000000",
      activityScoreThreshold: "55",
    },
  },
] as const;

export const baseSymbolUniverse: BaseSymbolData[] = [
  {
    symbol: "BBAI",
    companyName: "BigBear.ai Holdings",
    sector: "AIインフラ",
    exchange: "NYSE",
    price: 3.42,
    dailyChangePct: 11.8,
    volume: 41300000,
    relativeVolume: 4.9,
    marketCapMillions: 420,
    volatilityExpansionPct: 61,
    momentumPersistencePct: 78,
    newsCountIncrease: 1,
    gapMovePct: 6.1,
    watchlistCount: 4180,
    priceHistory: [2.67, 2.81, 2.95, 3.04, 3.17, 3.29, 3.42],
    scoreHistory: [64, 68, 71, 74, 79, 82, 86],
    summarySeed: "企業向け AI 契約の見出し後に板が引き締まりました",
    scanCadence: "5分",
  },
  {
    symbol: "QBTS",
    companyName: "D-Wave Quantum",
    sector: "量子",
    exchange: "NYSE",
    price: 1.88,
    dailyChangePct: 14.6,
    volume: 58200000,
    relativeVolume: 5.4,
    marketCapMillions: 540,
    volatilityExpansionPct: 69,
    momentumPersistencePct: 73,
    newsCountIncrease: 2,
    gapMovePct: 4.8,
    watchlistCount: 5360,
    priceHistory: [1.31, 1.42, 1.51, 1.58, 1.67, 1.74, 1.88],
    scoreHistory: [66, 69, 72, 75, 80, 84, 88],
    summarySeed: "量子テーマへの連想買いが投機的な追随を伴いました",
    scanCadence: "5分",
  },
  {
    symbol: "TNYA",
    companyName: "Tenaya Therapeutics",
    sector: "バイオテック",
    exchange: "NASDAQ",
    price: 1.37,
    dailyChangePct: 12.1,
    volume: 19400000,
    relativeVolume: 6.2,
    marketCapMillions: 210,
    volatilityExpansionPct: 76,
    momentumPersistencePct: 62,
    newsCountIncrease: 5,
    gapMovePct: 8.4,
    watchlistCount: 2940,
    priceHistory: [0.94, 1.01, 1.09, 1.11, 1.18, 1.26, 1.37],
    scoreHistory: [58, 61, 65, 70, 76, 84, 91],
    summarySeed: "新たな治験マイルストーンで遺伝子治療の思惑が加速しました",
    scanCadence: "5分",
  },
  {
    symbol: "SABS",
    companyName: "SAB Biotherapeutics",
    sector: "バイオテック",
    exchange: "NASDAQ",
    price: 0.89,
    dailyChangePct: 16.7,
    volume: 34100000,
    relativeVolume: 8.8,
    marketCapMillions: 82,
    volatilityExpansionPct: 92,
    momentumPersistencePct: 58,
    newsCountIncrease: 2,
    gapMovePct: 9.5,
    watchlistCount: 1880,
    priceHistory: [0.52, 0.57, 0.6, 0.66, 0.72, 0.78, 0.89],
    scoreHistory: [55, 59, 63, 69, 77, 86, 93],
    summarySeed: "ヘルスケア材料を受けて低流動性が値動きを増幅しました",
    scanCadence: "5分",
  },
  {
    symbol: "EVGO",
    companyName: "EVgo",
    sector: "EVインフラ",
    exchange: "NASDAQ",
    price: 4.18,
    dailyChangePct: 9.8,
    volume: 28500000,
    relativeVolume: 3.8,
    marketCapMillions: 1100,
    volatilityExpansionPct: 52,
    momentumPersistencePct: 69,
    newsCountIncrease: 1,
    gapMovePct: 5.0,
    watchlistCount: 3720,
    priceHistory: [3.41, 3.52, 3.61, 3.73, 3.86, 3.97, 4.18],
    scoreHistory: [57, 60, 63, 67, 72, 78, 83],
    summarySeed: "リスク選好の改善で充電インフラ株が一斉に買われました",
    scanCadence: "5分",
  },
  {
    symbol: "ARDX",
    companyName: "Ardelyx",
    sector: "バイオテック",
    exchange: "NASDAQ",
    price: 6.14,
    dailyChangePct: 7.3,
    volume: 17100000,
    relativeVolume: 3.2,
    marketCapMillions: 1450,
    volatilityExpansionPct: 39,
    momentumPersistencePct: 71,
    newsCountIncrease: 0,
    gapMovePct: 2.2,
    watchlistCount: 2520,
    priceHistory: [5.18, 5.34, 5.46, 5.57, 5.71, 5.84, 6.14],
    scoreHistory: [52, 54, 57, 60, 66, 71, 76],
    summarySeed: "バイオの物色が第一波を超えて広がり、じり高が続きました",
    scanCadence: "10分",
  },
  {
    symbol: "KULR",
    companyName: "KULR Technology Group",
    sector: "クリーンテック",
    exchange: "AMEX",
    price: 1.21,
    dailyChangePct: 6.4,
    volume: 25200000,
    relativeVolume: 4.4,
    marketCapMillions: 268,
    volatilityExpansionPct: 49,
    momentumPersistencePct: 70,
    newsCountIncrease: 1,
    gapMovePct: 2.0,
    watchlistCount: 2260,
    priceHistory: [0.86, 0.94, 1.0, 1.06, 1.11, 1.16, 1.21],
    scoreHistory: [49, 52, 56, 61, 67, 73, 78],
    summarySeed: "バッテリー安全性テーマと個人投資家の勢いが継続しました",
    scanCadence: "10分",
  },
  {
    symbol: "CRNC",
    companyName: "Cerence",
    sector: "産業ソフトウェア",
    exchange: "NASDAQ",
    price: 7.86,
    dailyChangePct: 5.1,
    volume: 6800000,
    relativeVolume: 2.6,
    marketCapMillions: 350,
    volatilityExpansionPct: 37,
    momentumPersistencePct: 63,
    newsCountIncrease: 1,
    gapMovePct: 2.9,
    watchlistCount: 1640,
    priceHistory: [6.48, 6.67, 6.91, 7.08, 7.26, 7.44, 7.86],
    scoreHistory: [44, 47, 52, 58, 64, 69, 73],
    summarySeed: "複数日ベースが保たれ、自動車ソフト株に買いが戻りました",
    scanCadence: "10分",
  },
  {
    symbol: "BKSY",
    companyName: "BlackSky Technology",
    sector: "宇宙テック",
    exchange: "NYSE",
    price: 12.46,
    dailyChangePct: 10.2,
    volume: 9800000,
    relativeVolume: 4.7,
    marketCapMillions: 1900,
    volatilityExpansionPct: 58,
    momentumPersistencePct: 74,
    newsCountIncrease: 2,
    gapMovePct: 4.4,
    watchlistCount: 3110,
    priceHistory: [9.84, 10.22, 10.74, 11.12, 11.45, 11.91, 12.46],
    scoreHistory: [59, 61, 65, 69, 74, 81, 85],
    summarySeed: "受注更新を受けて防衛関連の宇宙株に勢いが入りました",
    scanCadence: "5分",
  },
  {
    symbol: "RXRX",
    companyName: "Recursion Pharmaceuticals",
    sector: "AIインフラ",
    exchange: "NASDAQ",
    price: 6.22,
    dailyChangePct: 4.7,
    volume: 18800000,
    relativeVolume: 3.1,
    marketCapMillions: 2200,
    volatilityExpansionPct: 36,
    momentumPersistencePct: 66,
    newsCountIncrease: 2,
    gapMovePct: 1.8,
    watchlistCount: 3480,
    priceHistory: [5.1, 5.24, 5.37, 5.58, 5.74, 5.96, 6.22],
    scoreHistory: [50, 53, 56, 60, 64, 69, 74],
    summarySeed: "相対出来高の改善とともに AI 創薬株が静かに締まりました",
    scanCadence: "10分",
  },
  {
    symbol: "SANA",
    companyName: "Sana Biotechnology",
    sector: "バイオテック",
    exchange: "NASDAQ",
    price: 3.05,
    dailyChangePct: -1.9,
    volume: 9300000,
    relativeVolume: 2.9,
    marketCapMillions: 710,
    volatilityExpansionPct: 29,
    momentumPersistencePct: 52,
    newsCountIncrease: 1,
    gapMovePct: -0.6,
    watchlistCount: 1320,
    priceHistory: [3.42, 3.38, 3.29, 3.2, 3.15, 3.11, 3.05],
    scoreHistory: [47, 45, 43, 42, 44, 48, 51],
    summarySeed: "引けにかけて鈍化しても参加者の厚みは維持されました",
    scanCadence: "10分",
  },
  {
    symbol: "KTOS",
    companyName: "Kratos Defense & Security",
    sector: "防衛",
    exchange: "NASDAQ",
    price: 18.24,
    dailyChangePct: 3.8,
    volume: 7400000,
    relativeVolume: 2.7,
    marketCapMillions: 2800,
    volatilityExpansionPct: 31,
    momentumPersistencePct: 77,
    newsCountIncrease: 1,
    gapMovePct: 1.3,
    watchlistCount: 2860,
    priceHistory: [15.92, 16.14, 16.53, 16.94, 17.22, 17.75, 18.24],
    scoreHistory: [46, 49, 53, 57, 62, 67, 71],
    summarySeed: "見出し主導ではないまま防衛需要がリーダーシップを支えました",
    scanCadence: "15分",
  },
] as const;

export const scanLogs: ScanLog[] = [
  {
    id: "scan-301",
    source: "デモ小型株ユニバース",
    status: "success",
    startedAt: "2026-03-10T09:25:00Z",
    completedAt: "2026-03-10T09:25:03Z",
    processedSymbols: 148,
    failedFetches: 0,
    note: "定時スキャンは予定どおり完了。",
  },
  {
    id: "scan-300",
    source: "デモ小型株ユニバース",
    status: "warning",
    startedAt: "2026-03-10T09:20:00Z",
    completedAt: "2026-03-10T09:20:04Z",
    processedSymbols: 148,
    failedFetches: 2,
    note: "仮の気配値プロバイダーで断続的なタイムアウトが発生。",
  },
  {
    id: "scan-299",
    source: "デモ小型株ユニバース",
    status: "success",
    startedAt: "2026-03-10T09:15:00Z",
    completedAt: "2026-03-10T09:15:02Z",
    processedSymbols: 148,
    failedFetches: 0,
    note: "出来高とスコアのキャッシュを更新。",
  },
  {
    id: "scan-298",
    source: "デモ小型株ユニバース",
    status: "failed",
    startedAt: "2026-03-10T09:10:00Z",
    completedAt: "2026-03-10T09:10:05Z",
    processedSymbols: 91,
    failedFetches: 17,
    note: "上流取得の劣化を模したため、手動再試行を推奨。",
  },
] as const;
